[package]
name = "tcapi-model"
version = "0.1.0"
edition = "2021"
authors = ["stackinspector"]
license = "MPL-2.0"
repository = "https://github.com/Berylsoft/tcapi"

[lib]
path = "lib.rs"
name = "tcapi_model"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-enum-str = "0.3"
